// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetPostByID(ctx context.Context, id int32) (Post, error)
}

var _ Querier = (*Queries)(nil)
