// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeletePostByID(ctx context.Context, id int32) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetPostByID(ctx context.Context, id int32) (Post, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	UpdatePostByID(ctx context.Context, arg UpdatePostByIDParams) (Post, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
